Create cd.yml
BondarencoM/KoziDataService pull request #21
Opened 2020-12-01 13:33 UTC by MolotovHammr

2020-12-02 13:17 UTC, BoostedPenguin submitted a review, later dismissed

2020-12-04 16:24 UTC, BondarencoM approved these changes, later dismissed

2020-12-05 13:05 UTC, oererenn approved these changes, later dismissed

2020-12-07 18:10 UTC, michaelbahchevanov requested changes
There are a few things that should be changed/fixed.

2020-12-07 18:11 UTC, michaelbahchevanov commented on .github/workflows/cd.yml
> +      run: docker build . -f Dockerfile -t molotovhammr/kozidataservice:lastest
It spells lastest where it should be latest

2020-12-07 18:11 UTC, michaelbahchevanov commented on .github/workflows/cd.yml
> +      run: docker build . -f Dockerfile -t molotovhammr/kozidataservice:lastest
```suggestion
      run: docker build . -f Dockerfile -t molotovhammr/kozidataservice:latest
```

2020-12-07 18:11 UTC, michaelbahchevanov commented on .github/workflows/cd.yml
> +      run: docker push molotovhammr/kozidataservice:latest
Whereas here it's spelled right.

2020-12-10 13:28 UTC, larsverp approved these changes, later dismissed
👏🏻

2020-12-10 13:40 UTC, BondarencoM commented
@michaelbahchevanov  Do you approve the fix?

2020-12-10 13:42 UTC, michaelbahchevanov approved these changes
That's great! 🚀

2020-12-10 13:45 UTC, merged